spring: 
   datasource: 
      username: resume_item_tracker 
      password: resume_item_tracker 
      url: jdbc:mysql://localhost:3306/resume_item_tracker
      
   jpa: 
      hibernate: 
         ddl-auto: update   
      show-sql: true
        